version: '3.1'
services:
  app:
    container_name: ingestion
    image: ingestion
    build: ./
    ports:
      - "8080:8080"
    environment:
      REDIS_PORT:          "6379"
    depends_on:
      - dbpostgresql
      - redis
  dbpostgresql:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=mydb
  redis:
    image: redis:alpine
    ports:
      - 6379:6379